<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMasterPage.master" AutoEventWireup="true" CodeFile="ManageTimeslot.aspx.cs" Inherits="ManageTimeslot" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <p>
        <br />
    </p>
    <p align="center">
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
            AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" BackColor="White" BorderColor="#CCCCCC" 
            BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" 
            GridLines="Horizontal" onrowdeleting="GridView1_RowDeleting1" 
            onrowediting="GridView1_RowEditing1" 
            onrowupdating="GridView1_RowUpdating1" 
            onrowcancelingedit="GridView1_RowCancelingEdit" Width="100%">
            <Columns>
                <asp:BoundField DataField="cinemaxid" HeaderText="Cinemax ID" ReadOnly="True" />
                <asp:BoundField DataField="screenid" HeaderText="Screen ID" ReadOnly="True" />
                <asp:BoundField DataField="timeslot" HeaderText="Time Slot" />
            </Columns>
            <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
            <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
            <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#242121" />
        </asp:GridView>
    </p>
    <p style="text-align: center">
                    <asp:Label ID="lblmsg" runat="server"></asp:Label>
                </p>
</asp:Content>

