<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMasterPage.master" AutoEventWireup="true" CodeFile="ManageShow.aspx.cs" Inherits="ManageShow" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">

        .style1
        {
            width: 100%;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    
    <table class="style1">
        <tr>
            <td style="text-align: center">
                MANAGE SHOWTIME</td>
        </tr>
        <tr>
            <td align="center">
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                    AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                    BackColor="White" BorderColor="#CCCCCC" BorderWidth="1px" 
                    CellPadding="4" ForeColor="Black" GridLines="Horizontal" 
                    onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing" 
                    onrowupdating="GridView1_RowUpdating" 
                    onselectedindexchanged="GridView1_SelctedIndexChanged" 
                    onrowcancelingedit="GridView1_RowCancelingEdit" 
                    onrowdatabound="GridView1_RowDataBound" BorderStyle="None" CellSpacing="4" 
                    Width="100%">
                    <Columns>
                        <asp:TemplateField HeaderText="CITY">
                            <EditItemTemplate>
                                <asp:Label ID="lblcity" runat="server" Text='<%# Eval("city") %>'></asp:Label>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblcity" runat="server" Text='<%# Eval("city") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="CINEMAX">
                            <EditItemTemplate>
                                <asp:Label ID="lblcinemax" runat="server" Text='<%# Eval("cinemax") %>'></asp:Label>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblcinemax" runat="server" Text='<%# Eval("cinemax") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="SCREEN">
                            <EditItemTemplate>
                                <asp:Label ID="lblscreenid" runat="server" Text='<%# Eval("screen") %>'></asp:Label>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblscreenid" runat="server" Text='<%# Eval("screen") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="MOVIE">
                            <EditItemTemplate>
                                <asp:DropDownList ID="DropDownList1" runat="server" DataSourceID="Movie" 
                                    DataTextField="name" DataValueField="name">
                                </asp:DropDownList>
                                <asp:SqlDataSource ID="Movie" runat="server" 
                                    ConnectionString="<%$ ConnectionStrings:dbTheaterConnectionString %>" 
                                    SelectCommand="SELECT [name] FROM [tblMovie]"></asp:SqlDataSource>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label1" runat="server" Text='<%# Eval("movie") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="SHOW TIME">
                            <EditItemTemplate>
                                <asp:CheckBoxList ID="CheckBoxList1" runat="server">
                                </asp:CheckBoxList>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label2" runat="server" Text='<%# Eval("showtime") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
                    <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="White" ForeColor="Black" 
                        HorizontalAlign="Right" />
                    <SelectedRowStyle BackColor="#CC3333" ForeColor="White" Font-Bold="True" />
                    <SortedAscendingCellStyle BackColor="#F7F7F7" />
                    <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
                    <SortedDescendingCellStyle BackColor="#E5E5E5" />
                    <SortedDescendingHeaderStyle BackColor="#242121" />
                </asp:GridView>
            </td>
        </tr>
        <tr>
            <td style="text-align: center">
                <asp:Label ID="lblmsg" runat="server"></asp:Label>
            </td>
        </tr>
    </table>
    <div>
    </div>
    
</asp:Content>

