<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMasterPage.master" AutoEventWireup="true" CodeFile="ManageScreen.aspx.cs" Inherits="ManageScreen" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <h1 style="text-align: center">
        Manage Screen Details</h1>
    <p style="text-align: center">
        &nbsp;</p>
    <p style="text-align: center">
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
            AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" BackColor="White" BorderColor="#CCCCCC" 
            BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" 
            GridLines="Horizontal" onpageindexchanging="GridView1_PageIndexChanging" 
            onrowcancelingedit="GridView1_RowCancelingEdit" 
            onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing" 
            onrowupdating="GridView1_RowUpdating" Width="100%">
            <Columns>
                <asp:BoundField DataField="screenid" HeaderText="Screen ID" ReadOnly="True" />
                <asp:BoundField DataField="cinemaxid" HeaderText="Cinemax ID" ReadOnly="True" />
                <asp:BoundField DataField="name" HeaderText="Screen Name" />
                <asp:BoundField DataField="totalseats" HeaderText="Total Seats" />
                <asp:BoundField DataField="platinum" HeaderText="Platinum Seats" />
                <asp:BoundField DataField="gold" HeaderText="Gold Seats" />
                <asp:BoundField DataField="silver" HeaderText="Silver Seats" />
            </Columns>
            <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
            <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
            <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#242121" />
        </asp:GridView>
    </p>
    <p style="text-align: center">
                <asp:Label ID="lblmsg" runat="server"></asp:Label>
                </p>
</asp:Content>

